kind: Secret
apiVersion: v1
metadata:
  name: apicast-stage-secret
  namespace: 3scale-demo
data:
  AdminPortalURL: >-
    aHR0cHM6Ly9lZjg1MDY2YzU3NGM4YjA2NGZkZmZiN2Y1NjhiMzc2NGMyYjBjNTBkNjg4ZmZiMmVlYTA0MDhmNzM2NmE1ZmQ1QDNzY2FsZS1hZG1pbi4zc2NhbGUuYXBwcy5jbHVzdGVyLWNrem00LmNrem00LnNhbmRib3gxODA0Lm9wZW50bGMuY29tLw==
type: Opaque
